# ==========================================
# GLOBAL BASE CONFIGURATION
# ==========================================
# Project:
name: "human-behavior-analysis"
version: "1.0.0"
# debug_mode: true

# Hardware:
device: "cpu" # Thiết bị chạy model: 'cuda' (GPU), 'cpu', hoặc 'mps' (Apple Silicon)
# device_id: 0            # ID của GPU nếu máy có nhiều card

# IO:
# source: 0               # Nguồn video: Đường dẫn file (.mp4), link RTSP camera, hoặc 0 (Webcam trực tiếp)
# save_video: true        # Có lưu video kết quả sau khi xử lý hay không
display_window: true # Có bật cửa sổ OpenCV để hiển thị real-time không

# Video:
target_fps: 30 # FPS mục tiêu khi xử lý
# resize_width: 1280      # Chuẩn hóa chiều rộng frame (giúp đồng bộ tốc độ xử lý)
# resize_height: 720      # Chuẩn hóa chiều cao frame

# Inference:
confidence_threshold: 0.5 # Ngưỡng tin cậy tối thiểu để nhận diện đối tượng
iou_threshold: 0.45 # Ngưỡng Non-Maximum Suppression (NMS IOU)
input_size: [640, 640] # Kích thước đầu vào của model YOLO (ví dụ: 640x640)

# Visualization:
bbox_thickness: 1 # Độ dày đường viền bounding box
text_scale: 0.6 # Kích thước chữ hiển thị trên màn hình
show_fps: true # Hiển thị chỉ số FPS lên góc màn hình
# Định dạng màu BGR cho OpenCVcolors
green: [0, 255, 0]
red: [255, 0, 0]
blue: [0, 0, 255] # Xanh lá (Trạng thái bình thường) # Cam (Cảnh báo nhẹ) # Đỏ (Phát hiện gian lận / vi phạm)

# Onnx inference
# CPU: CPUExecutionProvider, OpenVINOExecutionProvider, XNNPACK
# NVIDIA GPU: CUDAExecutionProvider, TensorRTExecutionProvider
# AMD GPU: ROCmExecutionProvider, MIGraphXExecutionProvider
# Mobile / Edge / NPU: CoreMLExecutionProvider (Apple), QNNExecutionProvider (Qualcomm), NNAPI (Android)
# Khác: DirectMLExecutionProvider (Windows DirectX), WebGPUExecutionProvider
providers: ["CPUExecutionProvider"]

# Config for yolo onnx
coco_object_classes : 
  [
    "0": "person",
    "1": "bicycle",
    "2": "car",
    "3": "motorcycle",
    "4": "airplane",
    "5": "bus",
    "6": "train",
    "7": "truck",
    "8": "boat",
    "9": "traffic light",
    "10": "fire hydrant",
    "11": "stop sign",
    "12": "parking meter",
    "13": "bench",
    "14": "bird",
    "15": "cat",
    "16": "dog",
    "17": "horse",
    "18": "sheep",
    "19": "cow",
    "20": "elephant",
    "21": "bear",
    "22": "zebra",
    "23": "giraffe",
    "24": "backpack",
    "25": "umbrella",
    "26": "handbag",
    "27": "tie",
    "28": "suitcase",
    "29": "frisbee",
    "30": "skis",
    "31": "snowboard",
    "32": "sports ball",
    "33": "kite",
    "34": "baseball bat",
    "35": "baseball glove",
    "36": "skateboard",
    "37": "surfboard",
    "38": "tennis racket",
    "39": "bottle",
    "40": "wine glass",
    "41": "cup",
    "42": "fork",
    "43": "knife",
    "44": "spoon",
    "45": "bowl",
    "46": "banana",
    "47": "apple",
    "48": "sandwich",
    "49": "orange",
    "50": "broccoli",
    "51": "carrot",
    "52": "hot dog",
    "53": "pizza",
    "54": "donut",
    "55": "cake",
    "56": "chair",
    "57": "couch",
    "58": "potted plant",
    "59": "bed",
    "60": "dining table",
    "61": "toilet",
    "62": "tv",
    "63": "laptop",
    "64": "mouse",
    "65": "remote",
    "66": "keyboard",
    "67": "cell phone",
    "68": "microwave",
    "69": "oven",
    "70": "toaster",
    "71": "sink",
    "72": "refrigerator",
    "73": "book",
    "74": "clock",
    "75": "vase",
    "76": "scissors",
    "77": "teddy bear",
    "78": "hair drier",
    "79": "toothbrush"
  ]

pose_keypoints:
  [
    "nose",
    "left_eye",
    "right_eye",
    "left_ear",
    "right_ear",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
  ]

pose_skeleton:
  [
    [16, 14],   # Mắt cá chân phải -> Đầu gối phải  
    [14, 12],   # Đầu gối phải -> Hông phải  
    [17, 15],   # Mắt cá chân trái -> Đầu gối trái (1-indexed hoặc 0-indexed tùy code vẽ)  
    [15, 13],   # Đầu gối trái -> Hông trái  
    [12, 13],   # Hông phải -> Hông trái  
    [6, 12],    # Vai phải -> Hông phải  
    [5, 11],    # Vai trái -> Hông trái  
    [5, 6],     # Vai trái -> Vai phải
    [6, 8],     # Vai phải -> Khuỷu tay phải
    [8, 10],    # Khuỷu tay phải -> Cổ tay phải  
    [5, 7],     # Vai trái -> Khuỷu tay trái
    [7, 9],     # Khuỷu tay trái -> Cổ tay trái
    [1, 2],     # Mắt trái -> Mắt phải
    [0, 1],     # Mũi -> Mắt trái
    [0, 2],     # Mũi -> Mắt phải
    [1, 3],     # Mắt trái -> Tai trái
    [2, 4],     # Mắt phải -> Tai phải
  ]